# Generated by Django 3.2.7 on 2021-10-06 18:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('start_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('github_username', models.CharField(max_length=200, null=True)),
                ('hubspot_id', models.TextField(max_length=300, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Workflow_type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('course_id', models.ManyToManyField(to='soyuz_app.Course')),
            ],
        ),
        migrations.CreateModel(
            name='Workflows',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed', models.BooleanField(default=False)),
                ('workFlow_type_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='soyuz_app.workflow_type')),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('batch_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='soyuz_app.batch')),
                ('users', models.ManyToManyField(to='soyuz_app.User')),
            ],
        ),
        migrations.AddField(
            model_name='batch',
            name='course_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='soyuz_app.course'),
        ),
        migrations.AddField(
            model_name='batch',
            name='users',
            field=models.ManyToManyField(blank=True, to='soyuz_app.User'),
        ),
    ]
