# Generated by Django 3.2.7 on 2021-11-24 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soyuz_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='slack_channel_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
