# Generated by Django 3.2.7 on 2022-01-16 05:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('soyuz_app', '0002_auto_20211219_1251'),
        ('soyuz_app', '0002_batch_max_capacity'),
    ]

    operations = [
    ]
