# Generated by Django 3.2.7 on 2022-01-05 03:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('soyuz_app', '0002_auto_20211219_1251'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='section_leader',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='section_leader', to=settings.AUTH_USER_MODEL),
        ),
    ]
