# Generated by Django 3.2.7 on 2022-01-10 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soyuz_app', '0002_batch_max_capacity'),
    ]

    operations = [
        migrations.AddField(
            model_name='batch',
            name='gcal_link',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
