# Generated by Django 3.2.7 on 2021-10-30 11:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('soyuz_app', '0003_auto_20211029_1522'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batch',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='soyuz_app.course'),
        ),
        migrations.AlterField(
            model_name='section',
            name='batch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='soyuz_app.batch'),
        ),
        migrations.AlterField(
            model_name='workflows',
            name='workFlow_type_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='soyuz_app.workflow_type'),
        ),
    ]
