# Generated by Django 3.2.7 on 2022-01-05 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soyuz_app', '0004_section_section_leader'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='zoom_meeting_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
