# Generated by Django 3.2.7 on 2022-01-13 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('soyuz_app', '0002_batch_max_capacity'),
        ('soyuz_app', '0005_section_zoom_meeting_id'),
    ]

    operations = [
    ]
