# Generated by Django 3.2.7 on 2022-01-14 03:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('soyuz_app', '0006_recordings'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Recordings',
            new_name='Recording',
        ),
    ]
