# Generated by Django 3.2.7 on 2022-01-13 12:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('soyuz_app', '0006_merge_20220113_1210'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recordings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=255)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='soyuz_app.section')),
            ],
        ),
    ]
